apiVersion: v1
kind: Service
metadata:
  name: safepass-service
spec:
  type: LoadBalancer
  selector:
    app: safepass
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007
